name = "hello_ada"
description = "A simple hello world application for testing the development container."
version = "0.1.0-dev"

authors = ["Michael Gardner"]
maintainers = ["Michael Gardner <mjgardner@abitofhelp.com>"]
maintainers-logins = ["abitofhelp"]
licenses = "BSD-3-Clause"
website = "https://github.com/abitofhelp/dev_container_ada"
tags = ["ada", "dev", "container", "dev-container", "docker", "nerdctl", "podman"]

executables = ["hello_ada"]
